language: erlang
install: 'true'
otp_release:
- 20.0
- 19.3
env:
  global:
  - REBAR_VSN=3.4.3
  - PATH=./rebar3-$REBAR_VSN:$PATH
  - ALPACA_VERSION_TO_USE=v0.2.8
  - ALPACA_BASE_URL=https://github.com/alpaca-lang/alpaca/releases/download/$ALPACA_VERSION_TO_USE
cache:
  directories:
  - .rebar3-$REBAR_VSN
  - /home/travis/.cache/rebar3
before_install:
  - if [ ! -f rebar3-$REBAR_VSN/rebar3 ]; then wget --no-check-certificate https://github.com/erlang/rebar3/archive/$REBAR_VSN.tar.gz; fi
  - if [ -f $REBAR_VSN.tar.gz ]; then tar xvzf $REBAR_VSN.tar.gz; fi
  - cd rebar3-$REBAR_VSN
  - if [ ! -f ./rebar3 ]; then ./bootstrap; fi
  - cd ..
script:
  - export ALPACA_BASE=alpaca_${TRAVIS_OTP_RELEASE}
  - export ALPACA_PKG=${ALPACA_BASE}.tgz
  - export ALPACA_TO_USE=${ALPACA_BASE_URL}/${ALPACA_PKG}
  - wget $ALPACA_TO_USE
  - tar xvzf $ALPACA_PKG
  - export ALPACA_ROOT=`pwd`/alpaca-${ALPACA_VERSION_TO_USE}_${TRAVIS_OTP_RELEASE}
  - echo "ALPACA_ROOT is set to ${ALPACA_ROOT}"
  - rebar3 eunit
  - rebar3 ct
